import {fireEvent,render,screen} from '@testing-library/react'
import {describe,expect,it,vi} from 'vitest'
import {ChordComposer} from '../components/ChordComposer'
import {App} from '../app/App'

describe('guided chord entry',()=>{
 it('builds a chord from musical choices',()=>{const save=vi.fn();render(<ChordComposer mode="add" onSave={save} onCancel={()=>{}}/>);fireEvent.click(screen.getByRole('button',{name:'A'}));fireEvent.click(screen.getByRole('button',{name:/Minor darker/}));fireEvent.click(screen.getByRole('button',{name:'Add Am'}));expect(save).toHaveBeenCalledWith('Am')})
 it('opens an existing chord for editing',()=>{render(<ChordComposer mode="edit" initialSymbol="E7" onSave={()=>{}} onCancel={()=>{}}/>);expect(screen.getByText('E7')).toBeTruthy();expect(screen.getByRole('button',{name:'Update to E7'})).toBeTruthy()})
 it('previews a shape match before explicitly adding it',()=>{const save=vi.fn();render(<ChordComposer mode="add" onSave={save} onCancel={()=>{}}/>);fireEvent.click(screen.getByRole('tab',{name:/Find from a shape/}));expect(screen.getByText('Selected match')).toBeTruthy();expect(save).not.toHaveBeenCalled();fireEvent.click(screen.getByRole('button',{name:'Add G'}));expect(save).toHaveBeenCalledWith('G',[3,2,0,0,3,3])})
 it('shows an old-to-new confirmation while editing from a shape',()=>{const save=vi.fn();render(<ChordComposer mode="edit" initialSymbol="E7" initialFrets={[0,2,0,1,0,0]} onSave={save} onCancel={()=>{}}/>);fireEvent.click(screen.getByRole('tab',{name:/Find from a shape/}));fireEvent.change(screen.getByLabelText('Six-string shape code'),{target:{value:'320033'}});expect(screen.getByText('Your fingering will be saved with the new name.')).toBeTruthy();fireEvent.click(screen.getByRole('button',{name:'Update chord to G'}));expect(save).toHaveBeenCalledWith('G',[3,2,0,0,3,3])})
 it('explains chord symbols with formulas and notes as they are chosen',()=>{render(<ChordComposer mode="add" onSave={()=>{}} onCancel={()=>{}}/>);fireEvent.click(screen.getByRole('button',{name:/Sus 4 lifted/}));expect(screen.getByText('Inside Csus4')).toBeTruthy();expect(screen.getByText('1 · 4 · 5')).toBeTruthy();expect(screen.getByText(/third is removed/)).toBeTruthy();expect(screen.getByText('Compare sus, add, 7, and maj7')).toBeTruthy()})
 it('updates the progression and reveals the saved custom shape',()=>{render(<App/>);fireEvent.click(screen.getByRole('button',{name:'Edit E'}));fireEvent.click(screen.getByRole('tab',{name:/Find from a shape/}));fireEvent.change(screen.getByLabelText('Six-string shape code'),{target:{value:'320033'}});fireEvent.click(screen.getByRole('button',{name:'Update chord to G'}));expect(screen.getByRole('button',{name:'Edit G'})).toBeTruthy();expect(screen.getByRole('heading',{name:'Choose your G shape'})).toBeTruthy();expect(screen.getByText(/Updated E to G; your shape is shown below/)).toBeTruthy()},15000)
})
