import {fireEvent,render,screen} from '@testing-library/react'
import {describe,expect,it,vi} from 'vitest'
import {App} from '../app/App'
import {SectionComposer} from '../components/SectionComposer'
import {SongMap} from '../components/SongMap'
import {createSong,newInstance,newSection,nextSectionSuggestions,sectionInsertionIndex,sectionPlacementGuidance} from '../core/song/sections'

describe('section creation choices',()=>{
 it('asks whether to reuse, vary, or start fresh when the type exists',()=>{const song=createSong(['E','Am']);song.sections[0]!.kind='verse';song.sections[0]!.name=undefined;const create=vi.fn();render(<SectionComposer song={song} anchorInstanceId={song.arrangement[0]!.id} onCreate={create} onCancel={()=>{}}/>);fireEvent.click(screen.getByRole('button',{name:/Verse Tell the story/}));expect(screen.getByRole('button',{name:/Reuse Verse/})).toBeTruthy();expect(screen.getByRole('button',{name:/Make a variation/})).toBeTruthy();expect(screen.getByRole('button',{name:/Write a new verse/})).toBeTruthy();fireEvent.click(screen.getByRole('button',{name:/Reuse Verse/}));expect(create).toHaveBeenCalledWith(expect.objectContaining({kind:'verse',mode:'reuse',sourceId:song.sections[0]!.id}))})
 it('offers whole-song evidence for a new type',()=>{const song=createSong(['E','Am']);render(<SectionComposer song={song} anchorInstanceId={song.arrangement[0]!.id} onCreate={()=>{}} onCancel={()=>{}}/>);fireEvent.click(screen.getByRole('button',{name:/Chorus Create the arrival/}));expect(screen.getByRole('button',{name:'Start blank'})).toBeTruthy();expect(screen.getAllByText('Why this works').length).toBe(3)})
 it('offers optional structural guidance for the exact insertion point',()=>{const song=createSong(['C','Am']);song.sections[0]!.kind='verse';song.sections[0]!.name=undefined;const chorus=newSection('chorus'),bridge=newSection('bridge');song.sections.push(chorus,bridge);const chorusInstance=newInstance(chorus.id),bridgeInstance=newInstance(bridge.id);song.arrangement.push(chorusInstance,bridgeInstance);render(<SectionComposer song={song} anchorInstanceId={chorusInstance.id} onCreate={()=>{}} onCancel={()=>{}}/>);expect(screen.queryByText(/A second verse returns/)).toBeNull();fireEvent.click(screen.getByRole('button',{name:'Suggest what could come next'}));expect(screen.getByText(/A second verse returns/)).toBeTruthy();expect(screen.getAllByText(/before the existing bridge/)).toHaveLength(3)})
 it('targets insertion controls to the chosen section and the beginning',()=>{const song=createSong(['G']);song.sections[0]!.kind='verse';song.sections[0]!.name=undefined;const add=vi.fn();render(<SongMap song={song} activeId={song.arrangement[0]!.id} playing={false} onSelect={()=>{}} onMove={()=>{}} onReorder={()=>{}} onRemove={()=>{}} onAdd={add} onEdit={()=>{}} onPlay={()=>{}}/>);fireEvent.click(screen.getByRole('button',{name:/Add beginning/}));expect(add).toHaveBeenLastCalledWith(song.arrangement[0]!.id,'before');fireEvent.click(screen.getByRole('button',{name:'Insert section after Verse'}));expect(add).toHaveBeenLastCalledWith(song.arrangement[0]!.id,'after')})
 it('offers to turn the opening verse music into an independent intro',()=>{const song=createSong(['C','E','Am']);song.sections[0]!.kind='verse';song.sections[0]!.name=undefined;const create=vi.fn();render(<SectionComposer song={song} anchorInstanceId={song.arrangement[0]!.id} position="before" onCreate={create} onCancel={()=>{}}/>);expect(screen.getByRole('heading',{name:'How should the song open?'})).toBeTruthy();fireEvent.click(screen.getByRole('button',{name:/Intro Set the scene/}));expect(screen.getByText(/music you have been using before the vocal begins/)).toBeTruthy();fireEvent.click(screen.getByRole('button',{name:/Use Verse’s music/}));expect(create).toHaveBeenCalledWith({kind:'intro',mode:'variation',sourceId:song.sections[0]!.id})})
})

describe('section role coaching',()=>{
 it('suggests returning to verse before an early bridge without declaring a rule',()=>{const song=createSong(['C']);song.sections[0]!.kind='verse';song.sections[0]!.name=undefined;const chorus=newSection('chorus'),bridge=newSection('bridge');song.sections.push(chorus,bridge);const chorusInstance=newInstance(chorus.id),bridgeInstance=newInstance(bridge.id);song.arrangement.push(chorusInstance,bridgeInstance);expect(nextSectionSuggestions(song,chorusInstance.id)[0]?.kind).toBe('verse');expect(nextSectionSuggestions(song,chorusInstance.id)[0]?.reason).toMatch(/placement alone does not define it|second verse/);expect(sectionPlacementGuidance(song,bridgeInstance.id,'bridge')).toMatch(/does not have to follow one exact section type/)})
 it('treats the beginning as a real insertion point and suggests an intro first',()=>{const song=createSong(['C']);song.sections[0]!.kind='verse';song.sections[0]!.name=undefined;expect(sectionInsertionIndex(song,song.arrangement[0]!.id,'before')).toBe(0);expect(nextSectionSuggestions(song,song.arrangement[0]!.id,'before')[0]).toMatchObject({kind:'intro'});expect(nextSectionSuggestions(song,song.arrangement[0]!.id,'before')[0]?.reason).toContain('before any singing begins')})
})

describe('opening flow',()=>{
 it('inserts a copied verse idea before the existing arrangement as an Intro',()=>{const {container}=render(<App/>);fireEvent.click(screen.getByRole('button',{name:/Add beginning/}));fireEvent.click(screen.getByRole('button',{name:/Intro Set the scene/}));fireEvent.click(screen.getByRole('button',{name:/Use Section 1’s music/}));expect([...container.querySelectorAll('.section-main > span')].map(node=>node.textContent).slice(0,2)).toEqual(['Intro','Section 1'])})
})
