import type {FretMap} from '../guitar/voicings'
import {sectionKinds,type ProgressionState,type SongState} from '../song/sections'

export interface SavedSong{id:string;name:string;song:SongState;tempo:number;updatedAt:string}
export interface SaveEnvelope{version:3;songs:SavedSong[]}
interface LegacyProgression{id:string;name:string;chords:string[];voicingIds?:(string|null)[];customFrets?:(FretMap|null)[];tempo:number;updatedAt:string}

const validFret=(fret:unknown)=>fret==null||(Number.isInteger(fret)&&Number(fret)>=0&&Number(fret)<=24)
function validProgression(value:unknown):value is ProgressionState{if(!value||typeof value!=='object')return false;const p=value as Partial<ProgressionState>;return Array.isArray(p.chords)&&p.chords.every(c=>typeof c==='string')&&Array.isArray(p.voicingIds)&&p.voicingIds.every(id=>id==null||typeof id==='string')&&Array.isArray(p.customFrets)&&p.customFrets.every(shape=>shape==null||(Array.isArray(shape)&&shape.length===6&&shape.every(validFret)))&&p.voicingIds.length===p.chords.length&&p.customFrets.length===p.chords.length}
function validLegacy(value:unknown):value is LegacyProgression{if(!value||typeof value!=='object')return false;const p=value as Partial<LegacyProgression>;return typeof p.id==='string'&&typeof p.name==='string'&&Array.isArray(p.chords)&&p.chords.every(c=>typeof c==='string')&&typeof p.tempo==='number'&&(!p.voicingIds||(Array.isArray(p.voicingIds)&&p.voicingIds.every(id=>id==null||typeof id==='string')))&&(!p.customFrets||(Array.isArray(p.customFrets)&&p.customFrets.every(shape=>shape==null||(Array.isArray(shape)&&shape.length===6&&shape.every(validFret)))))}
function validSong(value:unknown):value is SongState{if(!value||typeof value!=='object')return false;const song=value as Partial<SongState>,kinds=new Set(sectionKinds.map(item=>item.id));return Array.isArray(song.sections)&&song.sections.length>0&&song.sections.every(section=>section&&typeof section.id==='string'&&kinds.has(section.kind)&&(!section.name||typeof section.name==='string')&&validProgression(section.progression))&&Array.isArray(song.arrangement)&&song.arrangement.length>0&&song.arrangement.every(instance=>instance&&typeof instance.id==='string'&&typeof instance.sectionId==='string'&&song.sections!.some(section=>section.id===instance.sectionId))}
function validSavedSong(value:unknown):value is SavedSong{if(!value||typeof value!=='object')return false;const item=value as Partial<SavedSong>;return typeof item.id==='string'&&typeof item.name==='string'&&typeof item.tempo==='number'&&typeof item.updatedAt==='string'&&validSong(item.song)}
export function isSaveEnvelope(value:unknown):value is SaveEnvelope{if(!value||typeof value!=='object')return false;const data=value as Partial<SaveEnvelope>;return data.version===3&&Array.isArray(data.songs)&&data.songs.every(validSavedSong)}
const migrate=(item:LegacyProgression):SavedSong=>{const sectionId=`legacy-section-${item.id}`;return{id:item.id,name:item.name,tempo:item.tempo,updatedAt:item.updatedAt,song:{sections:[{id:sectionId,kind:'custom',name:'Section 1',progression:{chords:[...item.chords],voicingIds:item.voicingIds?.length===item.chords.length?[...item.voicingIds]:item.chords.map(()=>null),customFrets:item.customFrets?.length===item.chords.length?item.customFrets.map(shape=>shape?[...shape] as FretMap:null):item.chords.map(()=>null)}}],arrangement:[{id:`legacy-instance-${item.id}`,sectionId}]}}}
export function readSavedSongs(value:unknown):SavedSong[]|null{if(isSaveEnvelope(value))return value.songs;if(!value||typeof value!=='object')return null;const legacy=value as {version?:unknown;progressions?:unknown};return(legacy.version===1||legacy.version===2)&&Array.isArray(legacy.progressions)&&legacy.progressions.every(validLegacy)?legacy.progressions.map(migrate):null}
export const serializeShare=(chords:string[],key?:string)=>{const q=new URLSearchParams({v:'1',chords:chords.join(',')});if(key)q.set('key',key);return `?${q}`}
export function parseShare(search:string):{chords:string[];key?:string}|null{const q=new URLSearchParams(search);if(q.get('v')!=='1')return null;const chords=q.get('chords')?.split(',').map(decodeURIComponent).filter(Boolean);if(!chords?.length||chords.length>32)return null;const key=q.get('key');return{chords,...(key?{key}:{})}}
