import type {FretMap} from '../guitar/voicings'
export interface SavedProgression{id:string;name:string;chords:string[];voicingIds?:(string|null)[];customFrets?:(FretMap|null)[];tempo:number;updatedAt:string}
export interface SaveEnvelope{version:2;progressions:SavedProgression[]}

function validProgression(value:unknown):value is SavedProgression{if(!value||typeof value!=='object')return false;const p=value as Partial<SavedProgression>;const validFret=(fret:unknown)=>fret==null||(Number.isInteger(fret)&&Number(fret)>=0&&Number(fret)<=24);return typeof p.id==='string'&&typeof p.name==='string'&&Array.isArray(p.chords)&&p.chords.every(c=>typeof c==='string')&&typeof p.tempo==='number'&&(!p.voicingIds||(Array.isArray(p.voicingIds)&&p.voicingIds.every(id=>id==null||typeof id==='string')))&&(!p.customFrets||(Array.isArray(p.customFrets)&&p.customFrets.every(shape=>shape==null||(Array.isArray(shape)&&shape.length===6&&shape.every(validFret)))))}
export function isSaveEnvelope(value:unknown):value is SaveEnvelope{if(!value||typeof value!=='object')return false;const d=value as Partial<SaveEnvelope>;return d.version===2&&Array.isArray(d.progressions)&&d.progressions.every(validProgression)}
export function readSavedProgressions(value:unknown):SavedProgression[]|null{if(isSaveEnvelope(value))return value.progressions;if(!value||typeof value!=='object')return null;const legacy=value as {version?:unknown;progressions?:unknown};return legacy.version===1&&Array.isArray(legacy.progressions)&&legacy.progressions.every(validProgression)?legacy.progressions.map(p=>({...p,voicingIds:p.chords.map(()=>null),customFrets:p.chords.map(()=>null)})):null}
export const serializeShare=(chords:string[],key?:string)=>{const q=new URLSearchParams({v:'1',chords:chords.join(',')});if(key)q.set('key',key);return `?${q}`}
export function parseShare(search:string):{chords:string[];key?:string}|null{const q=new URLSearchParams(search);if(q.get('v')!=='1')return null;const chords=q.get('chords')?.split(',').map(decodeURIComponent).filter(Boolean);if(!chords?.length||chords.length>32)return null;const key=q.get('key');return{chords,...(key?{key}:{})}}
