import {parseChord,sharedPitchClasses} from '../theory/chords'; import type {KeyInterpretation} from '../theory/types'
export type Direction='keep'|'build'|'resolve'|'darker'|'brighter'|'bigger'|'pull'|'chorus'|'loop'|'unexpected'
export interface Suggestion{id:string;title:string;path:string[];category:string;feeling:string;explanation:string;evidence:string[];score:number}
const A:Suggestion[]=[
{id:'am-f-c-g',title:'Open the horizon',path:['F','C','G'],category:'Natural',feeling:'wide · familiar',explanation:'F opens the harmony outward, then C and G keep the path singable without fully settling it.',evidence:['VI → III → VII in A minor','All three have practical open shapes','F and Am share A and C'],score:82},
{id:'am-dm-e',title:'Lean into the pull',path:['Dm','E7','Am'],category:'Resolve',feeling:'purposeful · returning',explanation:'Dm deepens the minor color before E7 creates a clear pull home to Am.',evidence:['iv → V7 → i cadence','G♯ in E7 resolves to A','Strong return to the selected tonic'],score:92},
{id:'am-c-b7',title:'Raise the stakes',path:['C','B7','E'],category:'Build',feeling:'tense · cinematic',explanation:'C keeps one foot in A minor while B7 redirects the energy toward E.',evidence:['C shares E with Am','B7 is the dominant of E','Chromatic D♯ adds directed tension'],score:77},
{id:'am-g-f-e',title:'Descending shadow',path:['G','F','E'],category:'Darker',feeling:'descending · inevitable',explanation:'A stepwise root descent gives the line gravity and ends on E, ready to pull back to Am.',evidence:['VII → VI → V','Descending bass contour','E preserves the loop back to Am'],score:86},
{id:'am-fm-c',title:'Side door',path:['Fm','C'],category:'Unexpected',feeling:'strange · connected',explanation:'Fm is outside the key, but its A♭ can slide into G while C provides a clear landing.',evidence:['Chromatic color with semitone motion','Fm and C share C','Practical guitar shapes'],score:68}]
const E:Suggestion[]=[
{id:'eam-b7',title:'Find the way back',path:['B7','E'],category:'Loop',feeling:'restless · homeward',explanation:'B7 turns the borrowed Am color back toward E with a direct dominant resolution.',evidence:['V7 → I in E major','D♯ rises to E','Strong loop ending'],score:93},
{id:'eam-c-g',title:'Keep the glow',path:['C','G','D'],category:'Natural',feeling:'open · anthemic',explanation:'C grows naturally from Am and opens into a familiar guitar-friendly chain.',evidence:['Am and C share A, C, and E','All open-position voicings','Smooth common-tone motion'],score:84},
{id:'eam-f',title:'Push past the edge',path:['F','G','E'],category:'Build',feeling:'rising · bold',explanation:'F and G lift in parallel before the unexpected drop back to E.',evidence:['Stepwise root climb','Borrowed ♭II and ♭III color','Contrasting return to I'],score:76},
{id:'eam-fmaj7',title:'Hold the high E',path:['Fmaj7','Cmaj7'],category:'Darker',feeling:'tender · suspended',explanation:'These shapes can keep the high E ringing, turning the color change into a continuous thread.',evidence:['Open high E pedal tone','Semitone bass movement A → F','Common tone connects each chord'],score:88},
{id:'eam-d-f',title:'Leave the map',path:['D','F','E'],category:'Unexpected',feeling:'surprising · grounded',explanation:'Two borrowed major chords widen the palette while their roots still lead cleanly back to E.',evidence:['♭VII → ♭II → I','F resolves by semitone to E','Familiar shapes, unfamiliar route'],score:66}]
const cats:Record<Direction,string[]>={keep:['Natural'],build:['Build'],resolve:['Resolve','Loop'],darker:['Darker'],brighter:['Natural'],bigger:['Build'],pull:['Natural'],chorus:['Build','Natural'],loop:['Loop','Resolve'],unexpected:['Unexpected']}
export function generateSuggestions(symbols:string[],key:KeyInterpretation|undefined,direction:Direction,preserveHighE:boolean,topNotes:number[]):Suggestion[]{const base=key?.id==='E-major'?E:A,last=parseChord(symbols.at(-1)??'');return base.map(s=>{let score=s.score;if(cats[direction].includes(s.category))score+=22;if(preserveHighE&&s.evidence.some(e=>e.toLowerCase().includes('high e')))score+=16;const first=parseChord(s.path[0]??'');if(last&&first)score+=sharedPitchClasses(last,first).length*2;if(topNotes.length&&first?.pitchClasses.includes((4+topNotes.at(-1)!)%12))score+=12;return{...s,score}}).sort((a,b)=>b.score-a.score)}
