import {useEffect,useMemo,useRef,useState} from 'react'
import {analyzeProgression,progressionEvidence} from '../core/theory/analysis'
import {parseChord} from '../core/theory/chords'
import {generateSuggestions,type Direction,type Suggestion} from '../core/suggestions/engine'
import {customVoicing,hasOpenHighE,midiNotes,voicingsFor,type FretMap,type GuitarRoute,type GuitarVoicing} from '../core/guitar/voicings'
import {highENotes,highETextTab} from '../core/context/topNotes'
import {parseShare,serializeShare,type SavedSong} from '../core/serialization/data'
import {cloneProgression,createSong,emptyProgression,linkedCount,newInstance,newSection,sectionKinds,sectionLabel,type ProgressionState,type SectionKind,type SongState} from '../core/song/sections'
import {browserClipboard,browserStorage} from '../platform/storage'
import {BrowserAudio} from '../platform/audio'
import {GuitarDiagram} from '../components/GuitarDiagram'
import {SuggestionCard} from '../components/SuggestionCard'
import {ChordComposer} from '../components/ChordComposer'
import {SongMap} from '../components/SongMap'
import {SectionComposer,type SectionCreateChoice} from '../components/SectionComposer'
import {SectionEditor} from '../components/SectionEditor'

const directions:{id:Direction;label:string;symbol:string}[]=[
 {id:'keep',label:'Keep this feeling',symbol:'≈'},{id:'build',label:'Build it up',symbol:'↗'},{id:'resolve',label:'Let it resolve',symbol:'⌄'},
 {id:'darker',label:'Get darker',symbol:'◐'},{id:'brighter',label:'Get brighter',symbol:'☼'},{id:'bigger',label:'Make it bigger',symbol:'✦'},
 {id:'pull',label:'Pull it back',symbol:'↙'},{id:'chorus',label:'Open into a chorus',symbol:'◎'},{id:'loop',label:'Make it loop',symbol:'↻'},
 {id:'unexpected',label:'Take me somewhere unexpected',symbol:'⌁'}]
type History={past:SongState[];present:SongState;future:SongState[]}
const initialShare=parseShare(window.location.search)
const initialChords=initialShare?.chords.every(c=>parseChord(c))?initialShare.chords:['E','Am']

export function App(){
 const initialState:ProgressionState={chords:initialChords,voicingIds:initialChords.map(c=>voicingsFor(c)[0]?.id??null),customFrets:initialChords.map(()=>null)}
 const [history,setHistory]=useState<History>(()=>{const song=createSong(initialState.chords,initialState.voicingIds,initialState.customFrets);return{past:[],present:song,future:[]}})
 const song=history.present
 const [activeInstanceId,setActiveInstanceId]=useState(song.arrangement[0]!.id)
 const activeInstance=song.arrangement.find(item=>item.id===activeInstanceId)??song.arrangement[0]!
 const activeSection=song.sections.find(item=>item.id===activeInstance.sectionId)??song.sections[0]!
 const {chords,voicingIds,customFrets}=activeSection.progression
 const commitSong=(next:SongState)=>setHistory(h=>({past:[...h.past,h.present].slice(-40),present:next,future:[]}))
 const commit=(next:ProgressionState)=>setHistory(h=>{const instance=h.present.arrangement.find(item=>item.id===activeInstanceId)??h.present.arrangement[0]!,present={...h.present,sections:h.present.sections.map(item=>item.id===instance.sectionId?{...item,progression:next}:item)};return{past:[...h.past,h.present].slice(-40),present,future:[]}})
 const selectedVoicings=chords.map((chord,index)=>customFrets[index]?customVoicing(chord,customFrets[index]!):voicingsFor(chord).find(v=>v.id===voicingIds[index])??voicingsFor(chord)[0])
 const availableVoicings=(index:number)=>{const regular=voicingsFor(chords[index]??'');return customFrets[index]&&selectedVoicings[index]?[selectedVoicings[index]!,...regular]:regular}
 const [editingChord,setEditingChord]=useState<number|'new'|null>(null)
 const [addingSection,setAddingSection]=useState(false)
 const [editingSection,setEditingSection]=useState(false)
 const [activeKey,setActiveKey]=useState(initialShare?.key??'A-minor')
 const [direction,setDirection]=useState<Direction>('keep')
 const [preserveHighE,setPreserveHighE]=useState(false)
 const [ringingAnswer,setRingingAnswer]=useState<'ask'|'yes'|'no'|'moves'>('ask')
 const [topNoteFrets,setTopNoteFrets]=useState([0,2,3])
 const [tempo,setTempo]=useState(86)
 const [loop,setLoop]=useState(false)
 const [playing,setPlaying]=useState<string|null>(null)
 const [expandedChord,setExpandedChord]=useState<number|null>(null)
 const [saves,setSaves]=useState<SavedSong[]>(()=>browserStorage.load())
 const [saveName,setSaveName]=useState('Untitled idea')
 const [notice,setNotice]=useState('')
 const [refine,setRefine]=useState(false)
 const [style,setStyle]=useState('')
 const audio=useRef(new BrowserAudio())
 const playToken=useRef(0)
 const interpretations=useMemo(()=>analyzeProgression(chords),[chords])
 const active=interpretations.find(k=>k.id===activeKey)??interpretations[0]
 const frets=topNoteFrets
 const highEAvailable=hasOpenHighE(chords.slice(0,2))
 const suggestions=useMemo(()=>generateSuggestions(chords,active,direction,preserveHighE,frets??[]),[chords,active,direction,preserveHighE,frets])
 useEffect(()=>{if(active&&!interpretations.some(k=>k.id===activeKey))setActiveKey(active.id)},[active,activeKey,interpretations])
 useEffect(()=>{if(expandedChord!=null&&!chords[expandedChord])setExpandedChord(null)},[chords,expandedChord])
 useEffect(()=>{if(!song.arrangement.some(item=>item.id===activeInstanceId))setActiveInstanceId(song.arrangement[0]!.id)},[song,activeInstanceId])
 const status=(message:string)=>{setNotice(message);window.setTimeout(()=>setNotice(''),2600)}
 const updateTopFret=(index:number,fret:number)=>setTopNoteFrets(items=>items.map((item,i)=>i===index?fret:item))
 const removeTopFret=(index:number)=>setTopNoteFrets(items=>items.length>1?items.filter((_,i)=>i!==index):items)
 const addChord=(value:string,frets?:FretMap)=>{const parsed=parseChord(value);if(!parsed)return;const addedIndex=chords.length;commit({chords:[...chords,parsed.normalized],voicingIds:[...voicingIds,frets?null:voicingsFor(parsed.normalized)[0]?.id??null],customFrets:[...customFrets,frets??null]});setEditingChord(null);setExpandedChord(frets?addedIndex:null);status(frets?`Added ${parsed.normalized} and saved shape ${frets.map(fret=>fret??'x').join('')}`:`Added ${parsed.normalized}`)}
 const updateChord=(index:number,value:string,frets?:FretMap)=>{const parsed=parseChord(value);if(!parsed)return;const previous=chords[index],next=[...chords],ids=[...voicingIds],custom=[...customFrets];next[index]=parsed.normalized;ids[index]=frets?null:voicingsFor(parsed.normalized)[0]?.id??null;custom[index]=frets??null;commit({chords:next,voicingIds:ids,customFrets:custom});setExpandedChord(frets?index:null);setEditingChord(null);status(frets?`Updated ${previous} to ${parsed.normalized}; your shape is shown below`:`Updated ${previous} to ${parsed.normalized}`)}
 const move=(index:number,by:number)=>{const next=[...chords],ids=[...voicingIds],custom=[...customFrets],target=index+by;if(target<0||target>=next.length)return;[next[index],next[target]]=[next[target]!,next[index]!];[ids[index],ids[target]]=[ids[target]!,ids[index]!];[custom[index],custom[target]]=[custom[target]!,custom[index]!];commit({chords:next,voicingIds:ids,customFrets:custom});setExpandedChord(open=>open===index?target:open===target?index:open)}
 const selectVoicing=(index:number,id:string)=>{const ids=[...voicingIds],custom=[...customFrets];ids[index]=id;custom[index]=null;commit({chords:[...chords],voicingIds:ids,customFrets:custom})}
 const duplicateChord=(index:number)=>commit({chords:[...chords.slice(0,index+1),chords[index]!,...chords.slice(index+1)],voicingIds:[...voicingIds.slice(0,index+1),voicingIds[index]??null,...voicingIds.slice(index+1)],customFrets:[...customFrets.slice(0,index+1),customFrets[index]??null,...customFrets.slice(index+1)]})
 const removeChord=(index:number)=>{commit({chords:chords.filter((_,i)=>i!==index),voicingIds:voicingIds.filter((_,i)=>i!==index),customFrets:customFrets.filter((_,i)=>i!==index)});setExpandedChord(null)}
 const stop=()=>{playToken.current++;audio.current.stop();setPlaying(null)}
 const playSymbols=async(symbols:string[],id:string)=>{if(!symbols.length){status('Add a chord before playing this section.');return}if(playing===id){stop();return}const token=++playToken.current;setPlaying(id);try{do{for(const symbol of symbols){if(playToken.current!==token)return;const chord=parseChord(symbol);if(chord)await audio.current.playChord(chord.pitchClasses,Math.max(.35,45/tempo));await new Promise(r=>setTimeout(r,60000/tempo))}}while(loop&&playToken.current===token)}catch{status('Audio could not start. Tap preview again or check browser sound permissions.')}finally{if(playToken.current===token)setPlaying(null)}}
 const playVoicings=async(items:GuitarVoicing[],id:string)=>{if(!items.length){status('Add a chord before playing this section.');return}if(playing===id){stop();return}const token=++playToken.current;setPlaying(id);try{do{for(const voicing of items){if(playToken.current!==token)return;await audio.current.playMidi(midiNotes(voicing),Math.max(.35,45/tempo));await new Promise(r=>setTimeout(r,60000/tempo))}}while(loop&&playToken.current===token)}catch{status('Audio could not start. Tap preview again or check browser sound permissions.')}finally{if(playToken.current===token)setPlaying(null)}}
 const voicingsIn=(progression:ProgressionState)=>progression.chords.map((chord,index)=>progression.customFrets[index]?customVoicing(chord,progression.customFrets[index]!):voicingsFor(chord).find(v=>v.id===progression.voicingIds[index])??voicingsFor(chord)[0])
 const playSong=async()=>{const id='full-song';if(!song.arrangement.some(instance=>song.sections.find(item=>item.id===instance.sectionId)?.progression.chords.length)){status('Add at least one chord before playing the song.');return}if(playing===id){stop();return}const token=++playToken.current;setPlaying(id);try{do{for(const instance of song.arrangement){const section=song.sections.find(item=>item.id===instance.sectionId);if(!section)continue;const shapes=voicingsIn(section.progression);for(let index=0;index<section.progression.chords.length;index++){if(playToken.current!==token)return;const voicing=shapes[index],chord=parseChord(section.progression.chords[index]!);if(voicing)await audio.current.playMidi(midiNotes(voicing),Math.max(.35,45/tempo));else if(chord)await audio.current.playChord(chord.pitchClasses,Math.max(.35,45/tempo));await new Promise(r=>setTimeout(r,60000/tempo))}}}while(loop&&playToken.current===token)}catch{status('Audio could not start. Tap play again or check browser sound permissions.')}finally{if(playToken.current===token)setPlaying(null)}}
 const addPath=(s:Suggestion,route?:GuitarRoute)=>{commit({chords:[...chords,...s.path],voicingIds:[...voicingIds,...(route?.voicings.map(v=>v.id)??s.path.map(c=>voicingsFor(c)[0]?.id??null))],customFrets:[...customFrets,...s.path.map(()=>null)]});status(`Added ${s.path.join(' → ')}${route?' with your guitar path':''}`)}
 const copy=async(text:string,label:string)=>{try{await browserClipboard.copy(text);status(`${label} copied`)}catch{status('Clipboard access was unavailable. Select the text and copy it manually.')}}
 const save=()=>{const item:SavedSong={id:crypto.randomUUID(),name:saveName.trim()||'Untitled song',song,tempo,updatedAt:new Date().toISOString()};const next=[item,...saves];setSaves(next);browserStorage.save(next);status('Song, sections, and guitar shapes saved on this device')}
 const share=async()=>{const url=`${location.origin}${location.pathname}${serializeShare(chords,active?.id)}`;window.history.replaceState(null,'',serializeShare(chords,active?.id));await copy(url,'Share link')}
 const removeSave=(id:string)=>{const next=saves.filter(s=>s.id!==id);setSaves(next);browserStorage.save(next)}
 const progressionFrom=(symbols:string[]):ProgressionState=>({chords:symbols,voicingIds:symbols.map(chord=>voicingsFor(chord)[0]?.id??null),customFrets:symbols.map(()=>null)})
 const addSongSection=(choice:SectionCreateChoice)=>{const source=song.sections.find(item=>item.id===choice.sourceId),sections=[...song.sections];let sectionId=source?.id;if(choice.mode!=='reuse'){const progression=choice.mode==='variation'&&source?cloneProgression(source.progression):choice.mode==='starter'&&choice.starter?progressionFrom(choice.starter.path):emptyProgression();const created=newSection(choice.kind,progression,choice.name);sections.push(created);sectionId=created.id}if(!sectionId)return;const instance=newInstance(sectionId),activeIndex=song.arrangement.findIndex(item=>item.id===activeInstanceId),arrangement=[...song.arrangement];arrangement.splice(Math.max(0,activeIndex+1),0,instance);commitSong({sections,arrangement});setActiveInstanceId(instance.id);setAddingSection(false);setEditingSection(false);status(`${choice.mode==='reuse'?'Reused':'Added'} ${sectionKinds.find(item=>item.id===choice.kind)?.label}`)}
 const moveSection=(id:string,by:number)=>{const arrangement=[...song.arrangement],index=arrangement.findIndex(item=>item.id===id),target=index+by;if(index<0||target<0||target>=arrangement.length)return;[arrangement[index],arrangement[target]]=[arrangement[target]!,arrangement[index]!];commitSong({...song,arrangement})}
 const reorderSection=(from:string,to:string)=>{const arrangement=[...song.arrangement],fromIndex=arrangement.findIndex(item=>item.id===from),toIndex=arrangement.findIndex(item=>item.id===to);if(fromIndex<0||toIndex<0)return;const [moved]=arrangement.splice(fromIndex,1);arrangement.splice(toIndex,0,moved!);commitSong({...song,arrangement})}
 const removeSection=(id:string)=>{if(song.arrangement.length===1||!confirm(`Remove ${sectionLabel(song,id)} from the song?`))return;const removed=song.arrangement.find(item=>item.id===id),arrangement=song.arrangement.filter(item=>item.id!==id),sections=removed&&arrangement.some(item=>item.sectionId===removed.sectionId)?song.sections:song.sections.filter(item=>item.id!==removed?.sectionId);commitSong({sections,arrangement});if(id===activeInstanceId)setActiveInstanceId(arrangement[Math.max(0,song.arrangement.findIndex(item=>item.id===id)-1)]!.id)}
 const updateSection=(kind:SectionKind,name?:string)=>{commitSong({...song,sections:song.sections.map(item=>item.id===activeSection.id?{...item,kind,name}:item)});setEditingSection(false);status('Section updated')}
 const makeVariation=()=>{if(linkedCount(song,activeSection.id)<2)return;const variation=newSection(activeSection.kind,activeSection.progression,activeSection.name),arrangement=song.arrangement.map(item=>item.id===activeInstanceId?{...item,sectionId:variation.id}:item);commitSong({sections:[...song.sections,variation],arrangement});status(`${sectionLabel(song,activeInstanceId)} is now an independent variation`)}
 const loadSong=(saved:SavedSong)=>{setHistory({past:[],present:saved.song,future:[]});setActiveInstanceId(saved.song.arrangement[0]!.id);setTempo(saved.tempo);setAddingSection(false);setEditingSection(false);status(`Loaded ${saved.name}`)}
 const analysisSummary=active?`${chords.join(' → ')}\n${active.romanNumerals.join(' → ')} in ${active.tonic} ${active.mode}\n${active.summary}`:'No analysis available'
 return <div className="app-shell">
  <header className="topbar"><a className="brand" href="/" aria-label="Progression Compass home"><span className="brand-mark">PC</span><span>Progression Compass<small>Songwriting field notes</small></span></a><div className="header-actions"><span className="saved-state"><i/> Local copy</span><details className="menu"><summary className="icon-button" aria-label="Open save and share menu">•••</summary><div className="menu-pop"><label>Song name<input value={saveName} onChange={e=>setSaveName(e.target.value)}/></label><button onClick={save}>Save complete song</button><button onClick={share}>Copy active section link</button><button onClick={()=>copy(chords.join(' → '),'Section chords')}>Copy section chords</button><button onClick={()=>copy(active?.romanNumerals.join(' → ')??'','Roman numerals')}>Copy numerals</button><button onClick={()=>copy(analysisSummary,'Analysis')}>Copy analysis</button>{saves.length>0&&<div className="saved-list"><span className="eyebrow">Saved songs</span>{saves.map(saved=><div key={saved.id}><button onClick={()=>loadSong(saved)}>{saved.name}<small>{saved.song.arrangement.length} sections · {saved.song.arrangement.flatMap(instance=>saved.song.sections.find(item=>item.id===instance.sectionId)?.progression.chords??[]).length} chords</small></button><button className="delete" onClick={()=>removeSave(saved.id)} aria-label={`Delete ${saved.name}`}>×</button></div>)}</div>}</div></details></div></header>
  <main>
   <section className="hero"><div className="folio-meta"><span>Working sheet 01</span><span>Standard tuning · guitar</span></div><span className="kicker">Current song</span><h1>{saveName.trim()||'Untitled idea'}</h1><p>Write down what your hands found. Shape it into sections, learn what the chords contain, and follow the next move that sounds honest.</p></section>
   <SongMap song={song} activeId={activeInstanceId} playing={playing==='full-song'} onSelect={id=>{setActiveInstanceId(id);setAddingSection(false);setEditingSection(false);setEditingChord(null);setExpandedChord(null)}} onMove={moveSection} onReorder={reorderSection} onRemove={removeSection} onAdd={()=>{setAddingSection(true);setEditingSection(false);setEditingChord(null);setExpandedChord(null)}} onEdit={()=>{setEditingSection(true);setAddingSection(false)}} onPlay={playSong}/>
   {addingSection&&<SectionComposer song={song} afterInstanceId={activeInstanceId} onCreate={addSongSection} onCancel={()=>setAddingSection(false)}/>}
   {editingSection&&<SectionEditor key={activeSection.id} section={activeSection} onSave={updateSection} onCancel={()=>setEditingSection(false)}/>}
   <section className="workbench" aria-labelledby="progression-title">
    <div className="section-heading"><div><span className="step">01</span><h2 id="progression-title">{sectionLabel(song,activeInstanceId)}</h2>{linkedCount(song,activeSection.id)>1&&<><span className="linked-badge">↗ Linked section</span><button className="variation-button" onClick={makeVariation}>Make variation</button></>}</div><div className="history-controls"><button onClick={()=>setHistory(h=>h.past.length?{past:h.past.slice(0,-1),present:h.past.at(-1)!,future:[h.present,...h.future]}:h)} disabled={!history.past.length}>↶ <span>Undo</span></button><button onClick={()=>setHistory(h=>h.future.length?{past:[...h.past,h.present],present:h.future[0]!,future:h.future.slice(1)}:h)} disabled={!history.future.length}>↷ <span>Redo</span></button></div></div>
    <div className="voicing-guide"><span className="string-icon">≋</span><p><strong>Explore the fretboard.</strong> Every chord with available voicings has a clearly marked shape button.</p></div>
    <div className="chord-row">{chords.map((chord,index)=>{const shapeCount=availableVoicings(index).length;return <div className="chord-wrap" key={index+chord}>{index>0&&<span className="arrow">→</span>}<article className={`chord-card ${expandedChord===index?'shape-active':''}`}><button className="chord-name" onClick={()=>{setEditingChord(index);setExpandedChord(null)}} aria-label={`Edit ${chord}`}>{chord}<small>{selectedVoicings[index]?.label??parseChord(chord)?.quality}</small><span className="edit-cue">Edit chord</span></button><div className="chord-tools"><button onClick={()=>move(index,-1)} disabled={index===0} aria-label={`Move ${chord} left`}>←</button><button onClick={()=>move(index,1)} disabled={index===chords.length-1} aria-label={`Move ${chord} right`}>→</button><button onClick={()=>duplicateChord(index)} aria-label={`Duplicate ${chord}`}>⧉</button><button onClick={()=>removeChord(index)} aria-label={`Remove ${chord}`}>×</button></div><button className="shape-toggle" disabled={!shapeCount} aria-expanded={expandedChord===index} aria-controls="shape-workspace" onClick={()=>{setExpandedChord(expandedChord===index?null:index);setEditingChord(null)}}><span className="shape-button-icon">≋</span><span><strong>{expandedChord===index?'Close shapes':'View shapes'}</strong><small>{shapeCount?`${shapeCount} options`:'Not available'}</small></span><b>{expandedChord===index?'↑':'↓'}</b></button></article></div>})}<button className="add-chord" onClick={()=>{setEditingChord('new');setExpandedChord(null)}} aria-expanded={editingChord==='new'}><span>Add chord</span><b>＋</b><small>Choose name or shape</small></button></div>
    {editingChord!==null&&<ChordComposer key={editingChord==='new'?'new':`${editingChord}-${chords[editingChord]}`} mode={editingChord==='new'?'add':'edit'} initialSymbol={editingChord==='new'?undefined:chords[editingChord]} initialFrets={editingChord==='new'?undefined:selectedVoicings[editingChord]?.frets} onCancel={()=>setEditingChord(null)} onSave={(symbol,frets)=>editingChord==='new'?addChord(symbol,frets):updateChord(editingChord,symbol,frets)}/>}
    {expandedChord!=null&&chords[expandedChord]&&<section className="shape-workspace" id="shape-workspace" aria-labelledby="shape-workspace-title"><header><div><span className="eyebrow">Guitar voicings</span><h3 id="shape-workspace-title">Choose your {chords[expandedChord]} shape</h3><p>Stay nearby for smooth movement, or jump to a new position when the song wants a change of scene.</p></div><button className="close-shapes" onClick={()=>setExpandedChord(null)} aria-label="Close chord shapes">×</button></header><div className="voicing-grid">{availableVoicings(expandedChord).map((voicing,option)=><article className={`voicing-option ${selectedVoicings[expandedChord]?.id===voicing.id?'selected':''}`} key={voicing.id}><div className="voicing-option-top"><span>{voicing.tags.includes('custom')?'Your shape':`Option ${option+1}`}</span>{selectedVoicings[expandedChord]?.id===voicing.id&&<b>Current shape</b>}</div><GuitarDiagram voicing={voicing}/><button onClick={()=>selectVoicing(expandedChord,voicing.id)} disabled={selectedVoicings[expandedChord]?.id===voicing.id}>{selectedVoicings[expandedChord]?.id===voicing.id?'Selected':'Use this shape'}</button></article>)}</div></section>}
    <div className="transport"><button className="play-main" onClick={()=>selectedVoicings.every(Boolean)?playVoicings(selectedVoicings as GuitarVoicing[],'progression'):playSymbols(chords,'progression')}>{playing==='progression'?'■':'▶'} <span>{playing==='progression'?'Stop':'Play selected shapes'}</span></button><label>Tempo <input type="range" min="50" max="180" value={tempo} onChange={e=>setTempo(Number(e.target.value))}/><b>{tempo}</b></label><button className={`loop ${loop?'on':''}`} onClick={()=>setLoop(!loop)} aria-pressed={loop}>↻ Loop</button><button className="clear" onClick={()=>{if(confirm('Clear this progression?')){commit({chords:[],voicingIds:[],customFrets:[]});setExpandedChord(null);setEditingChord(null)}}}>Clear</button></div>
   </section>
   <section className="tonal panel">
    <div className="section-heading"><div><span className="step">02</span><h2>A couple ways to hear it</h2></div><span className="uncertain">Harmony can be ambiguous</span></div>
    <div className="key-grid">{interpretations.slice(0,2).map(k=><button className={`key-card ${active?.id===k.id?'active':''}`} onClick={()=>setActiveKey(k.id)} key={k.id}><span className="radio"/><span><strong>{k.tonic} {k.mode}</strong><small>{k.label}</small></span><b>{k.romanNumerals.join(' → ')}</b></button>)}</div>
    {active&&<div className="interpretation"><span className="quote-mark">“</span><p>{active.summary}</p><details><summary>Go deeper into the theory</summary><div className="theory-detail"><p>Roman numerals describe each chord’s relationship to the selected home key. Uppercase usually means major; lowercase means minor; ♭ marks a lowered scale degree.</p><ul>{progressionEvidence(chords).map(e=><li key={e}>{e}</li>)}</ul></div></details></div>}
   </section>
   <section className="direction panel">
    <div className="section-heading"><div><span className="step">03</span><h2>What should the idea do next?</h2></div><span className="optional">Optional — change this anytime</span></div>
    <div className="direction-grid">{directions.map(d=><button key={d.id} className={direction===d.id?'active':''} onClick={()=>setDirection(d.id)}><span>{d.symbol}</span>{d.label}</button>)}</div>
    {highEAvailable&&ringingAnswer==='ask'&&<div className="context-prompt"><span className="string-icon">≋</span><div><strong>Both guitar shapes keep the high E ringing.</strong><p>Is that part of the sound you want to preserve?</p></div><div><button onClick={()=>{setPreserveHighE(true);setRingingAnswer('yes')}}>Keep it ringing</button><button onClick={()=>setRingingAnswer('no')}>Doesn’t matter</button><button onClick={()=>setRingingAnswer('moves')}>I move that note</button></div></div>}
    {ringingAnswer==='moves'&&<div className="top-note fret-movement"><div className="movement-heading"><span className="eyebrow">High E string movement</span><strong>Build the note path</strong><small>Choose each fret. The arrows appear automatically.</small></div><div className="fret-sequence">{frets.map((fret,index)=><div className="fret-step" key={index}><label><span>Step {index+1}</span><select value={fret} onChange={event=>updateTopFret(index,Number(event.target.value))}>{Array.from({length:25},(_,f)=><option value={f} key={f}>{f} · {highENotes([f])[0]}</option>)}</select></label><button onClick={()=>removeTopFret(index)} disabled={frets.length===1} aria-label={`Remove step ${index+1}`}>×</button>{index<frets.length-1&&<b>→</b>}</div>)}{frets.length<8&&<button className="add-fret" onClick={()=>setTopNoteFrets(items=>[...items,items.at(-1)??0])}>＋ Add step</button>}</div><div className="movement-preview"><code>{highETextTab(frets)}</code><span>{highENotes(frets).join(' → ')}</span></div></div>}
    <details className="refine" open={refine} onToggle={e=>setRefine(e.currentTarget.open)}><summary>Refine suggestions <span>Style, section & movement</span></summary><div className="refine-grid"><div className="section-context"><span>Section context</span><strong>{sectionKinds.find(item=>item.id===activeSection.kind)?.label}</strong><small>The engine uses this role when starting neighboring sections.</small></div><label>General style<select value={style} onChange={e=>setStyle(e.target.value)}><option value="">Not specified</option><option>Pop</option><option>Rock</option><option>Indie</option><option>Folk</option><option>Cinematic</option><option>R&amp;B</option></select></label><p>These details gently shape the creative framing. Core harmony remains based on the chords and selected home key.</p></div></details>
   </section>
   <section className="suggestions panel"><div className="section-heading"><div><span className="step">04</span><h2>Possible next moves</h2></div><span className="updated">↻ Shaped for “{directions.find(d=>d.id===direction)?.label}”</span></div><div className="suggestion-grid">{suggestions.slice(0,5).map(s=><SuggestionCard key={s.id} suggestion={s} playing={playing===s.id} routePlaying={playing===`${s.id}:guitar`} anchor={selectedVoicings.at(-1)} onPreview={()=>playSymbols([...chords,...s.path],s.id)} onPreviewRoute={route=>playVoicings([...selectedVoicings.filter((v):v is GuitarVoicing=>Boolean(v)),...route.voicings],`${s.id}:guitar`)} onChooseRoute={route=>addPath(s,route)} onAdd={()=>addPath(s)}/>)}</div><p className="ear-note">These are routes, not rules. Your ear gets the final say.</p></section>
  </main>
  <footer><span className="brand-mark">PC</span><p><strong>Progression Compass</strong><br/>A working page for unfinished songs.</p><span>Saved locally.<br/>No account. No tracking.</span></footer>
  <div className="toast" role="status" aria-live="polite">{notice}</div>
 </div>
}

