import {useMemo,useState} from 'react'
import {sectionKinds,type SectionKind,type SectionStarter,type SongState} from '../core/song/sections'
import {wholeSongSectionStarters} from '../core/song/sectionSuggestions'

export type SectionCreateChoice={kind:SectionKind;mode:'reuse'|'variation'|'blank'|'starter';sourceId?:string;starter?:SectionStarter;name?:string}
export function SectionComposer({song,afterInstanceId,onCreate,onCancel}:{song:SongState;afterInstanceId:string;onCreate:(choice:SectionCreateChoice)=>void;onCancel:()=>void}){
 const [kind,setKind]=useState<SectionKind|null>(null),[fresh,setFresh]=useState(false),[name,setName]=useState('')
 const existing=kind?song.sections.filter(section=>section.kind===kind):[],starters=useMemo(()=>kind?wholeSongSectionStarters(song,afterInstanceId,kind):[],[song,afterInstanceId,kind])
 return <section className="section-composer"><header><div><span className="eyebrow">Build the song</span><h3>{kind?`Add ${sectionKinds.find(item=>item.id===kind)?.label}`:'What comes next?'}</h3><p>{kind?'Choose whether this section reuses an idea or begins somewhere new.':'A label gives the engine a useful intention, never a rigid formula.'}</p></div><button className="close-shapes" onClick={onCancel} aria-label="Close add section panel">×</button></header>
 {!kind?<div className="section-kind-grid">{sectionKinds.map(item=><button onClick={()=>setKind(item.id)} key={item.id}><strong>{item.label}</strong><small>{item.purpose}</small></button>)}</div>:<>
  {kind==='custom'&&<label className="custom-section-name"><span>Section name</span><input value={name} onChange={event=>setName(event.target.value)} placeholder="e.g. Refrain or Solo"/></label>}
  {existing.length&&!fresh?<div className="section-origin"><button onClick={()=>onCreate({kind,mode:'reuse',sourceId:existing[0]!.id,name:name||undefined})}><b>↗</b><span><strong>Reuse {existing[0]!.name||sectionKinds.find(item=>item.id===kind)?.label}</strong><small>Keep both appearances linked. Changes update everywhere.</small></span></button><button onClick={()=>onCreate({kind,mode:'variation',sourceId:existing[0]!.id,name:name||undefined})}><b>≈</b><span><strong>Create a variation</strong><small>Copy its chords and shapes, then edit independently.</small></span></button><button onClick={()=>setFresh(true)}><b>＋</b><span><strong>Start a new {sectionKinds.find(item=>item.id===kind)?.label.toLowerCase()}</strong><small>Begin blank or ask for whole-song-aware starting ideas.</small></span></button></div>:<div className="fresh-section"><div className="starter-heading"><span className="composer-label">Suggested for this song</span><button onClick={()=>onCreate({kind,mode:'blank',name:name||undefined})}>Start completely blank</button></div>{starters[0]?.evidence[0]&&<div className="song-context-note"><b>Listening to the whole song</b><span>{starters[0].evidence[0]}</span></div>}<div className="starter-grid">{starters.map(starter=><article key={starter.id}><button className="starter-choice" onClick={()=>onCreate({kind,mode:'starter',starter,name:name||undefined})}><strong>{starter.title}</strong><span>{starter.path.join(' → ')}</span><small>{starter.description}</small></button><details><summary>Why this fits your song</summary><ul>{starter.evidence.map(item=><li key={item}>{item}</li>)}</ul></details></article>)}</div></div>}
  <button className="back-section" onClick={()=>{if(fresh&&existing.length)setFresh(false);else setKind(null)}}>← Back</button>
 </>}
 </section>
}
