import {useMemo,useState} from 'react'
import {nextSectionSuggestions,sectionKinds,sectionLabel,type SectionKind,type SectionStarter,type SongState} from '../core/song/sections'
import {wholeSongSectionStarters} from '../core/song/sectionSuggestions'

export type SectionCreateChoice={kind:SectionKind;mode:'reuse'|'variation'|'blank'|'starter';sourceId?:string;starter?:SectionStarter;name?:string}
export function SectionComposer({song,afterInstanceId,onCreate,onCancel}:{song:SongState;afterInstanceId:string;onCreate:(choice:SectionCreateChoice)=>void;onCancel:()=>void}){
 const [kind,setKind]=useState<SectionKind|null>(null),[fresh,setFresh]=useState(false),[name,setName]=useState(''),[showIdeas,setShowIdeas]=useState(false)
 const existing=kind?song.sections.filter(section=>section.kind===kind):[],starters=useMemo(()=>kind?wholeSongSectionStarters(song,afterInstanceId,kind):[],[song,afterInstanceId,kind])
 const roleIdeas=useMemo(()=>nextSectionSuggestions(song,afterInstanceId),[song,afterInstanceId])
 const label=sectionKinds.find(item=>item.id===kind)?.label
 return <section className="section-composer"><header><div><span className="composer-overline">Insert after {sectionLabel(song,afterInstanceId)}</span><h3>{kind?label:'What comes next?'}</h3><p>{kind?'Reuse something you wrote, or begin a new idea.':'Choose the job this part should do in the song—or ask for a structural nudge.'}</p></div><button className="close-shapes" onClick={onCancel} aria-label="Close add section panel">×</button></header>
 {!kind?<><div className="role-nudge"><button className="button" aria-expanded={showIdeas} onClick={()=>setShowIdeas(value=>!value)}>{showIdeas?'Hide structural ideas':'Suggest what could come next'}</button><span>Optional guidance, never a rule.</span></div>{showIdeas&&<div className="role-suggestions">{roleIdeas.map((idea,index)=>{const definition=sectionKinds.find(item=>item.id===idea.kind)!;return <button onClick={()=>setKind(idea.kind)} key={idea.kind}><span>{String(index+1).padStart(2,'0')}</span><strong>{definition.label}</strong><small>{idea.reason}</small><b>Choose →</b></button>})}</div>}<div className="section-kind-heading"><span>Or choose the role yourself</span></div><div className="section-kind-grid">{sectionKinds.map((item,index)=><button onClick={()=>setKind(item.id)} key={item.id}><span>{String(index+1).padStart(2,'0')}</span><strong>{item.label}</strong><small>{item.purpose}</small><b>→</b></button>)}</div></>:<>
  {kind==='custom'&&<label className="custom-section-name"><span>Section name</span><input value={name} onChange={event=>setName(event.target.value)} placeholder="e.g. Refrain or Solo"/></label>}
  {existing.length&&!fresh?<div className="section-origin"><button onClick={()=>onCreate({kind,mode:'reuse',sourceId:existing[0]!.id,name:name||undefined})}><b>↗</b><span><strong>Reuse {existing[0]!.name||label}</strong><small>Keep both appearances linked.</small></span></button><button onClick={()=>onCreate({kind,mode:'variation',sourceId:existing[0]!.id,name:name||undefined})}><b>≈</b><span><strong>Make a variation</strong><small>Copy it, then edit independently.</small></span></button><button onClick={()=>setFresh(true)}><b>＋</b><span><strong>Write a new {label?.toLowerCase()}</strong><small>Start blank or use a song-aware suggestion.</small></span></button></div>:<div className="fresh-section"><div className="starter-heading"><span>Starting points</span><button onClick={()=>onCreate({kind,mode:'blank',name:name||undefined})}>Start blank</button></div>{starters[0]?.evidence[0]&&<p className="song-context-line"><b>Song context</b>{starters[0].evidence[0]}</p>}<div className="starter-list">{starters.map((starter,index)=><article key={starter.id}><button className="starter-choice" onClick={()=>onCreate({kind,mode:'starter',starter,name:name||undefined})}><span className="starter-number">{String(index+1).padStart(2,'0')}</span><span className="starter-copy"><strong>{starter.path.join(' → ')}</strong><small>{starter.title}</small></span><b>Use</b></button><details><summary>Why this works</summary><ul>{starter.evidence.map(item=><li key={item}>{item}</li>)}</ul></details></article>)}</div></div>}
  <button className="back-section" onClick={()=>{if(fresh&&existing.length)setFresh(false);else setKind(null)}}>← Back</button>
 </>}
 </section>
}
